CREATE OR REPLACE TRIGGER controlDeletSocio
BEFORE DELETE ON SOCIO
FOR EACH ROW
begin

  DELETE FROM COOPEXSOCIO WHERE SOCIO = :OLD.IDSOCIO;

exception
  when OTHERS then
    DBMS_OUTPUT.PUT_LINE(SQLERRM||' '||sqlcode);
end;
/